### PR TITLE
Backwards compatibility for 3.3.2

### PR DESCRIPTION
**Pull request by jan-janssen**
Please do not merge this in the `main` branch, but rather create a new branch and merge these changes there. So 3.3.2 can be released in addition to 4.0.0 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by thewchan** [comment]
@jan-janssen Got it, I've pushed the v3.3.2 branch and change the base branch on this PR.

**Comment by thewchan** [comment]
@conda-forge-admin please rerun ci

**Comment by thewchan** [comment]
@jan-janssen not sure what's going on, something weird with the CI or outage at conda-forge, I'll check again later

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
